server:
  port: 9092

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sudip-samanta/spring-cloud-config-server-repository
          clone-on-start: true
